### ISSUE TITLE
Invalidate

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-device-address#4]
Let's say I slipped on my keyboard ( `%nplJ+lzs8zMogccDO3TOmJb9jqV18sEA6sCrfWHLU8s=.sha256` ). I guess setting `--availability 0` is the right thing to do then?

**Comment by dominictarr** [comment]
oh right, well it currently won't let you set `availability=0`
https://github.com/ssbc/ssb-device-address/blob/master/index.js#L94-L95

but there should be a way to cancel. what about `--cancel` or `--unannounce` ? or `--no-address` (same as: `{address: false}`?)

**Comment by dominictarr** [comment]
and then if `address === false` it disables the address.

**Comment by cryptix** [comment]
uhm... I was able to use `--availability 0`: `%A+2xCQn1AoRTnX6nNv/CLNwl1JdLa5d0j2q2YZL+BWU=.sha256` I just wanted to make sure it's the correct way.



I'd be against `--no-address` becasue you might have multiple and which one are you invalidating then? unannounce also sounds contra to append-only.

**Comment by dominictarr** [comment]
You can only have one address. but a multiserver address can contain multiple addresses.
Since a public key is tied to a feed, and a feed should only exist on one device, and unlike `pub` announcements, with device-address you can only speak for your self - no nominating addresses for others... it seemed reasonable to just publish a new address and that overrides the old one.

Did you create the announcement using [`sbot deviceAddress.announce`](https://github.com/ssbc/ssb-device-address#announceaddress-addr-availability0-1-cb--post-the-current-address-or-addr-if-given) or by just publishing the message? (the former will give you an error if you provide a availability of 0)

Usually I would look at how a setting would currently behave and draw an analogy from there - but at this point the only thing which directly uses this is ssb-user-invites which [sorts messages by hops then availability](https://github.com/ssbc/ssb-user-invites/blob/master/index.js#L293-L298) that means your friends will still use that address, although it will be sorted after other peers with the same hops.

That means it doesn't quite do the right thing.

**Comment by cryptix** [comment]
> (the former will give you an error if you provide a availability of 0) 

no I didn't somehow. I published the message above from the cli.

> You can only have one address.

Oh.. okay I wouldn't have assumed that. But if that's the case: can I create a private `--rcpt` address while having another public address on that feed?

> Since a public key is tied to a feed

because of this it seems redundant to post the full multiserv address. especially when having multiple ones. the invite generate can still construct the full qualifier for the receiver to dial the right thing, no?

**Comment by cryptix** [comment]
Also regarding all-in-one: I have to specify the availability for all the link types/services at once and need to update the whole thing when one of them changes.

**Comment by dominictarr** [comment]
Oh well the purpose of multiple addresses in this case is that you may support for example - both tcp and web sockets - so that browsers can also talk to you, or maybe you support shs and shs2... etc, this is about enabling you to update protocols. it's more about different paths to the device rather than the device being in different places.

Are you expecting to have lots of addresses to manage for one device? if so can you explain what you are thinking.
